name: Docker Image Staging CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: []

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare NuGet.Config
      uses: datamonsters/replace-action@v2
      with:
        files: 'NuGet.Config.actions'
        replacements: '%%username%%=xivk,%%token%%=${{ secrets.PACKAGES_SECRET }}'
    - run: mv NuGet.Config.actions NuGet.Config 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Publish project
      run: dotnet publish -c release
      working-directory: ./src/BikeDataProject.Registrations.API/
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bikedataproject/registration-api:staging
      working-directory: ./src/BikeDataProject.Registrations.API/
    - name: Login to GitHub Packages with Docker
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u anywaysoopen --password-stdin
    - name: Tag the Docker image
      run: docker tag bikedataproject/registration-api:staging
      working-directory: ./src/BikeDataProject.Registrations.API/
    - name: Build the Docker image for the package
      run: docker build -t bikedataproject/registration-api:staging .
      working-directory: ./src/BikeDataProject.Registrations.API/
    - name: Publish the image to GitHub packages.
      run: docker push bikedataproject/registration-api:staging
      working-directory: ./src/BikeDataProject.Registrations.API/
