name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        source-url: https://nuget.pkg.github.com/bikedataproject/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.PACKAGES_SECRET }}
    - name: Prepare Nuget.Config
      uses: BjornLuG/substitute-string-action@v1
      id: sub
      with:
        _input-file: NuGet.Config.actions
        username: xivk
    - run: car NuGet.Config.actions
    - name: Install dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
